# Generated by Django 4.2.4 on 2024-05-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contato",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=200)),
                ("telefone", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "contato",
                "ordering": ["-id"],
            },
        ),
    ]
