# Generated by Django 4.2.4 on 2023-09-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contato",
            name="nome",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
