# Generated by Django 4.2.4 on 2024-05-25 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_contato_nome"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contato",
        ),
    ]
